// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using docugen.Data;

#nullable disable

namespace docugen.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251121221542_Fields3")]
    partial class Fields3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("docugen.Models.CvData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("templateId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("templateId");

                    b.HasIndex("userId");

                    b.ToTable("curriculums");
                });

            modelBuilder.Entity("docugen.Models.EducacionItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Carrera")
                        .HasColumnType("longtext");

                    b.Property<int?>("CvDataid")
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Graduacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Institucion")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CvDataid");

                    b.ToTable("educacionItems");
                });

            modelBuilder.Entity("docugen.Models.HabilidadItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CvDataid")
                        .HasColumnType("int");

                    b.Property<string>("Habilidad")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CvDataid");

                    b.ToTable("habilidadItems");
                });

            modelBuilder.Entity("docugen.Models.InteresItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CvDataid")
                        .HasColumnType("int");

                    b.Property<string>("Interes")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CvDataid");

                    b.ToTable("interesItems");
                });

            modelBuilder.Entity("docugen.Models.PdfTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("pdfTemplates");
                });

            modelBuilder.Entity("docugen.Models.TrabajoItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CvDataid")
                        .HasColumnType("int");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Final")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Inicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CvDataid");

                    b.ToTable("trabajoItems");
                });

            modelBuilder.Entity("docugen.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("docugen.Models.CvData", b =>
                {
                    b.HasOne("docugen.Models.PdfTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("templateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("docugen.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("user");
                });

            modelBuilder.Entity("docugen.Models.EducacionItem", b =>
                {
                    b.HasOne("docugen.Models.CvData", null)
                        .WithMany("Educacion")
                        .HasForeignKey("CvDataid");
                });

            modelBuilder.Entity("docugen.Models.HabilidadItem", b =>
                {
                    b.HasOne("docugen.Models.CvData", null)
                        .WithMany("Habilidades")
                        .HasForeignKey("CvDataid");
                });

            modelBuilder.Entity("docugen.Models.InteresItem", b =>
                {
                    b.HasOne("docugen.Models.CvData", null)
                        .WithMany("Intereses")
                        .HasForeignKey("CvDataid");
                });

            modelBuilder.Entity("docugen.Models.TrabajoItem", b =>
                {
                    b.HasOne("docugen.Models.CvData", null)
                        .WithMany("Trabajo")
                        .HasForeignKey("CvDataid");
                });

            modelBuilder.Entity("docugen.Models.CvData", b =>
                {
                    b.Navigation("Educacion");

                    b.Navigation("Habilidades");

                    b.Navigation("Intereses");

                    b.Navigation("Trabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
